import { ATTENTION_FOCUS, JUDGMENT_FUNCTION, LIFESTYLE, MBTI_SINGLE_TEMPLATE_TYPE, PERCEPTION_FUNCTION, UNKOWN } from "src/pkg";

const OPPOSITES_MAP = {
  [ATTENTION_FOCUS.EXTRAVERTED]: ATTENTION_FOCUS.INTROVERTED,
  [ATTENTION_FOCUS.INTROVERTED]: ATTENTION_FOCUS.EXTRAVERTED,
  [PERCEPTION_FUNCTION.SENSING]: PERCEPTION_FUNCTION.INTUITION,
  [PERCEPTION_FUNCTION.INTUITION]: PERCEPTION_FUNCTION.SENSING,
  [JUDGMENT_FUNCTION.THINKING]: JUDGMENT_FUNCTION.FEELING,
  [JUDGMENT_FUNCTION.FEELING]: JUDGMENT_FUNCTION.THINKING,
  [LIFESTYLE.JUDGING]: LIFESTYLE.PERCEIVING,
  [LIFESTYLE.PERCEIVING]: LIFESTYLE.JUDGING,
  [UNKOWN.UNKOWN]: UNKOWN.UNKOWN
} as const;

export type INVERT_TYPE<T extends MBTI_SINGLE_TEMPLATE_TYPE> = (typeof OPPOSITES_MAP)[T];
